//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wema_CAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionAudit
    {
        public long ActionId { get; set; }
        public Nullable<long> CAMId { get; set; }
        public string Action { get; set; }
        public string FromUserId { get; set; }
        public string Designation { get; set; }
        public string DestinationUserId { get; set; }
        public Nullable<System.DateTime> DateActionPerformed { get; set; }
    }
}
