//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wema_CAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public string BranchId { get; set; }
        public string BranchName { get; set; }
        public int ZoneId { get; set; }
        public int RegionId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> DateLastUpdated { get; set; }
        public string UpdateUserId { get; set; }
        public string BranchShortCode { get; set; }
    }
}
