//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wema_CAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAM_User
    {
        public long id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string EmailAddress { get; set; }
        public string Role { get; set; }
        public string BranchId { get; set; }
        public int ZoneId { get; set; }
        public int RegionId { get; set; }
        public string Grade { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<bool> CanApprove { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime DateLastUpdated { get; set; }
        public string UpdateUserId { get; set; }
    }
}
