//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wema_CAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fileinformation
    {
        public long fileid { get; set; }
        public Nullable<long> CAMId { get; set; }
        public string filename { get; set; }
        public string filepath { get; set; }
    }
}
