//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wema_CAM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Wema_CAMEntities : DbContext
    {
        public Wema_CAMEntities()
            : base("name=Wema_CAMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Zone> Zone { get; set; }
        public DbSet<Branch> Branch { get; set; }
        public DbSet<Region> Region { get; set; }
        public DbSet<sampleJTE> sampleJTE { get; set; }
        public DbSet<ApplicantType> ApplicantType { get; set; }
        public DbSet<State> State { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<UserFunction> UserFunction { get; set; }
        public DbSet<ApprovalLimit> ApprovalLimit { get; set; }
        public DbSet<Comment> Comment { get; set; }
        public DbSet<ActionAudit> ActionAudit { get; set; }
        public DbSet<Audit> Audit { get; set; }
        public DbSet<FacilityType> FacilityType { get; set; }
        public DbSet<ApplicationType> ApplicationType { get; set; }
        public DbSet<IndustryType> IndustryType { get; set; }
        public DbSet<fileinformation> fileinformation { get; set; }
        public DbSet<CAM_User> CAM_User { get; set; }
        public DbSet<CAM> CAM { get; set; }
        public DbSet<CreditRequestSummary> CreditRequestSummary { get; set; }
        public DbSet<AdditionalComment> AdditionalComment { get; set; }
        public DbSet<ApplicantsBrief> ApplicantsBrief { get; set; }
    }
}
